name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron:  "30 20 * * *"

jobs:
  call_workflow:
    name: Run Trivy Scan Workflow
    uses: ballerina-platform/ballerina-library/.github/workflows/trivy-scan-template.yml@main
    secrets: inherit
